### ISSUE TITLE
Plugin not working

### ISSUE THREAD

**Issue by fabiomcosta** [ariel-frischer/bmessages.nvim#15]
When running `Bmessages` an empty window opens up.
Running `messages` I can see multiple messages on my panel.

Running `lua= vim.api.nvim_cmd({ cmd = "messages" }, { output = true })` I see this is always returning an empty string instead of the expected content, and that seems to be the reason why the plugin doesn't work, but I don't know why this is happening in my case.

https://github.com/ariel-frischer/bmessages.nvim/blob/main/lua/bmessages.lua#L39

I really wish it worked though, it would be much better than the standard messages panel.
Thank you!

**Comment by ariel-frischer** [comment]
That is unfortunate, what version of neovim are you using? `nvim --version`
Does this: `lua= vim.api.nvim_exec2('messages', { output = true })` give you an output table?
How about `lua= vim.api.nvim_command("messages")` ?

Additionally, maybe try checking `:checkhealth` and running Bmessages as the only plugin if possible.

**Comment by fabiomcosta** [comment]
Ok so it is for sure https://github.com/folke/noice.nvim, I uninstalled only it and it solved the issue.
My guess is that I should be able to fix the issue by playing with its configuration flags

Thank you!

**Comment by fabiomcosta** [comment]
Indeed with the following noice config I'm able to keep noice installed and working along with Bmessages:
```
    require('noice').setup({
      messages = {
        enabled = false,
      },
    })
```

🥳

**Comment by tan-wei** [comment]
Does it mean that it will conflict with noice.nvim when enabled messages in it?
