### ISSUE TITLE
Please provide instructions for Packer installation

### ISSUE THREAD

**Issue by elmarsto** [ariel-frischer/bmessages.nvim#5]
Hi, I don't lazy.nvim and I'm not sure how to map the fields of the example conf you provided onto what I use. 

Looks good, but passing for now, because I can't figure out how to install.

**Comment by ariel-frischer** [comment]
Hey thanks for pointing that out, I'll be sure to test it out with packer before adding it into the README.md and keep you posted.

**Comment by ariel-frischer** [comment]
Try this: 
  
  ```lua
  use {
  "ariel-frischer/bmessages.nvim",
    config = function()
      require("bmessages").setup({
        -- config here or empty for defaults
      })
    end,
  }
```

Still have to get packer working on my end but that should work.

**Comment by elmarsto** [comment]
Thank you for this! Installed and it appears to be working great! What an improvement over vanilla :messages. <3
