### ISSUE TITLE
Why this plugin is so huge

### ISSUE THREAD

**Issue by sassanh** [ariel-frischer/bmessages.nvim#8]
I noticed bmessages.nvim is cloning git submodules like plenary.nvim instead of having them in its dependencies. It is causing redundancy, it would be nice if we could improve it.

**Comment by ariel-frischer** [comment]
Thats a good point, I did notice this as well. Perhaps I can remove plenary entirely. It came with the original repo: https://github.com/m00qek/plugin-template.nvim
I'll dig into this later today.

**Comment by ariel-frischer** [comment]
I've removed the submodule, its not needed for the actual plugin but is for testing. Try uninstall, reinstall or lazy sync should be much faster now.

**Comment by sassanh** [comment]
Thanks! Yes it is much smaller now.
